### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by umer-fa** [hammadtq/binance-php-sdk#1]
aslam u alakum
                          i am using your code binance-php-sdk and i am facing some problems can you please help me? you code is working good no issue in code just when i am posting transaction hex to testnet server then response i'm getting following response
 {
  "code": 401,
  "failed_tx_index": 0,
  "message": "signature verification failed",
  "success_tx_results": []
}
can you please check for me?
i am very thankful to you.

                                                                                                       regards 
                                                                                        Umer Farooq (PHP developer)

**Comment by hammadtq** [comment]
Walikum Salam,

I will need more info as in what methods you are using etc. If you can please make an isolated test and post it here that will be useful.

**Comment by umer-fa** [comment]
Aslam u alakum

i am newbie to this domain.
please help me. 
i am using your example from transaction folder file transfer.PHP and just use my own drived public() key and private key nothing else i am using. Following keys i am using and this is the code of this file i am using.
file name transfer.php
<?php

namespace Binance\Examples\Transactions;

require '../../../vendor/autoload.php';

use Binance\Client\BncClient;
$privateKey = '0081cc0e50682c8155e57a71cc3131a6db5eef0eba40f99ebab50305f889bd5a';
$bncClient = new BncClient('http://185.244.248.31:26657');
$bncClient->chooseNetwork("testnet"); // or this can be "mainnet"
//$bncClient->initChain();
$bncClient->setPrivateKey($privateKey);

$response = $bncClient->transfer("tbnb1hn8ym9xht925jkncjpf7lhjnax6z8nv2mu9wy3", "tbnb1e63sdtthg3juu8dk2l2j6h7llfeqdw5uefc09q", 0.02, "BNB", "34213423");

var_dump($response);

**Comment by umer-fa** [comment]
can you please check you example with name transfer.php. please do this. i am very thankful to you.

**Comment by hammadtq** [comment]
> Aslam u alakum
> 
> i am newbie to this domain.
> please help me.
> i am using your example from transaction folder file transfer.PHP and just use my own drived public() key and private key nothing else i am using. Following keys i am using and this is the code of this file i am using.
> file name transfer.php
> 
> chooseNetwork("testnet"); // or this can be "mainnet" //$bncClient->initChain(); $bncClient->setPrivateKey($privateKey); $response = $bncClient->transfer("tbnb1hn8ym9xht925jkncjpf7lhjnax6z8nv2mu9wy3", "tbnb1e63sdtthg3juu8dk2l2j6h7llfeqdw5uefc09q", 0.02, "BNB", "34213423"); var_dump($response);

Please post the error that you are getting from this request.

**Comment by umer-fa** [comment]
i am using this code in transfer.php. from your src/Examples/Transactions/
private key =  0081cc0e50682c8155e57a71cc3131a6db5eef0eba40f99ebab50305f889bd5a
<?php
namespace Binance\Examples\Transactions;
require '../../../vendor/autoload.php';
use Binance\Client\BncClient;
$privateKey = '0081cc0e50682c8155e57a71cc3131a6db5eef0eba40f99ebab50305f889bd5a';
$bncClient = new BncClient('https://data-seed-pre-2-s1.binance.org');
$bncClient->chooseNetwork("testnet"); // or this can be "mainnet"
//$bncClient->initChain();
$bncClient->setPrivateKey($privateKey);

$response = $bncClient->transfer("tbnb1hn8ym9xht925jkncjpf7lhjnax6z8nv2mu9wy3", "tbnb1e63sdtthg3juu8dk2l2j6h7llfeqdw5uefc09q", 0.02, "BNB", "34213423");

var_dump($response);
?>

and getting this response 

{
"code": 401,
"failed_tx_index": 0,
"message": "signature verification failed",
"success_tx_results": []
}

**Comment by hammadtq** [comment]
> i am using this code in transfer.php. from your src/Examples/Transactions/
> private key = 0081cc0e50682c8155e57a71cc3131a6db5eef0eba40f99ebab50305f889bd5a
> 
> chooseNetwork("testnet"); // or this can be "mainnet" //$bncClient->initChain(); $bncClient->setPrivateKey($privateKey); $response = $bncClient->transfer("tbnb1hn8ym9xht925jkncjpf7lhjnax6z8nv2mu9wy3", "tbnb1e63sdtthg3juu8dk2l2j6h7llfeqdw5uefc09q", 0.02, "BNB", "34213423"); var_dump($response); ?>
> and getting this response
> 
> {
> "code": 401,
> "failed_tx_index": 0,
> "message": "signature verification failed",
> "success_tx_results": []
> }

Is the example working fine with the private key there in the original example code?

**Comment by umer-fa** [comment]
> > i am using this code in transfer.php. from your src/Examples/Transactions/
> > private key = 0081cc0e50682c8155e57a71cc3131a6db5eef0eba40f99ebab50305f889bd5a
> > chooseNetwork("testnet"); // or this can be "mainnet" //$bncClient->initChain(); $bncClient->setPrivateKey($privateKey); $response = $bncClient->transfer("tbnb1hn8ym9xht925jkncjpf7lhjnax6z8nv2mu9wy3", "tbnb1e63sdtthg3juu8dk2l2j6h7llfeqdw5uefc09q", 0.02, "BNB", "34213423"); var_dump($response); ?>
> > and getting this response
> > {
> > "code": 401,
> > "failed_tx_index": 0,
> > "message": "signature verification failed",
> > "success_tx_results": []
> > }
> 
> Is the example working fine with the private key there in the original example code?

Yes. its working fine. just you need update GuzzleHttp client with new version.
when you runn this code  with same this private and drive public keys there will be no issue. you will get response as i am getting.. 

Transfer.php using BncClient class method transfer , transfer return _prepareTransaction method result and then the result send to HttpClient class and then that class send this to gusslehttp method SendPost. at that position you can get this error

**Comment by umer-fa** [comment]
can you please check this example file? Transfer.php

**Comment by ImAbdullahJan** [comment]
Hi @umer-fa you can downgrade your GuzzleHttp client if you are getting error with the new version.

**Comment by umer-fa** [comment]
@ImAbdullahJan i have check this in Guzzlehttp client old version i am getting reponse from server['signature verification failed']. i want to know is there any problem with the code creating signature please check that..

**Comment by umer-fa** [comment]
you can run my code 

> > > i am using this code in transfer.php. from your src/Examples/Transactions/
> > > private key = 0081cc0e50682c8155e57a71cc3131a6db5eef0eba40f99ebab50305f889bd5a
> > > chooseNetwork("testnet"); // or this can be "mainnet" //$bncClient->initChain(); $bncClient->setPrivateKey($privateKey); $response = $bncClient->transfer("tbnb1hn8ym9xht925jkncjpf7lhjnax6z8nv2mu9wy3", "tbnb1e63sdtthg3juu8dk2l2j6h7llfeqdw5uefc09q", 0.02, "BNB", "34213423"); var_dump($response); ?>
> > > and getting this response
> > > {
> > > "code": 401,
> > > "failed_tx_index": 0,
> > > "message": "signature verification failed",
> > > "success_tx_results": []
> > > }
> > 
> > 
> > Is the example working fine with the private key there in the original example code?
> 
> Yes. its working fine. just you need update GuzzleHttp client with new version.
> when you runn this code with same this private and drive public keys there will be no issue. you will get response as i am getting..
> 
> Transfer.php using BncClient class method transfer , transfer return _prepareTransaction method result and then the result send to HttpClient class and then that class send this to gusslehttp method SendPost. at that position you can get this error

@ImAbdullahJan you can check by excute this code in examples/transaction/transfer.php i hope you will got point that i want to explain.

**Comment by umer-fa** [comment]
i am getting encoding transaction code that is

c901F0625DEE0a4a2a2c87fa0a210a14bcce4d94d75955495a789053efde53e9b423cd8a12090a03424e421080897a12210a14cea306ad774465ce1db657d52d5fdffa7206ba9c12090a03424e421080897a126d0a26eb5ae98721031c5c39bde9ac209d8297aa080dc41fac1b2b50a9cfa5c6306b9fd8cc760a44791240d7893c3d7b7c11f15419575c855f1294dcfe9ad6d7d8e18a861fe80d4949b9cd6a767a22bb4ba62511f1415dfc7d821864e7f1155a3ac874be0d5de754211dba18d7501a083334323133343233

this code i am getting from @hammadtq library mean its working mean code is working fine. but when

post on this url 
https://testnet-dex.binance.org/api/v1/broadcast?sync=1

its response 
{
  "code": 401,
  "failed_tx_index": 0,
  "message": "signature verification failed",
  "success_tx_results": []
}

its mean something in @hammadtq library missing in creating signature code that i am not finding.

i am posting this without using Guzzlehttp client and getting same response.

**Comment by ImAbdullahJan** [comment]
Hi @umer-fa, I cannot understand your problem clearly. You can call on this number +92 333 4716150.

**Comment by umer-fa** [comment]
Thanks @hammadtq and @ImAbdullahJan for you time i got my mistake thanks a lot you..
