### ISSUE TITLE
Does it support PHP8?

### ISSUE THREAD

**Issue by wartw** [hammadtq/binance-php-sdk#8]
Does it support PHP8?
The official PHP SDK is not supported. Now you are the only one who has written it.

**Comment by hammadtq** [comment]
I have never tried running it with PHP8 as I am no longer maintaining it, maybe you can try and see if it works.

**Comment by wartw** [comment]
Now only secp256k1 on PHP8 has a problem and may need your help, secp256k1 may be able to use https://github.com/kornrunner/php-secp256k1
I'm not very familiar with encryption

**Comment by wartw** [comment]
Everything else I can change has been changed.
